' Copyright (c) Microsoft Corporation.  All rights reserved.
'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports PInvoke
Imports Xunit

'''<summary>
'''This is a test class for PInvoke.NativeSymbolIterator and is intended
'''to contain all PInvoke.NativeSymbolIterator Unit Tests
'''</summary>
Public Class NativeSymbolIteratorTest

    Private Sub EnsureIsSymbol(ByVal sym As NativeSymbol, ByVal list As List(Of NativeSymbolRelationship))
        For Each rel As NativeSymbolRelationship In list
            If Object.ReferenceEquals(sym, rel.Symbol) Then
                Return
            End If
        Next

        Throw New Exception("Could Not find the symbol")
    End Sub

    Private Sub EnsureIsParent(ByVal sym As NativeSymbol, ByVal list As List(Of NativeSymbolRelationship))
        For Each rel As NativeSymbolRelationship In list
            If Object.ReferenceEquals(sym, rel.Parent) Then
                Return
            End If
        Next

        Throw New Exception("Could Not find the symbol")
    End Sub

    '''<summary>
    ''' Make sure that the original parent is returned
    '''</summary>
    <Fact>
    Public Sub FindAllRelationships1()
        Dim ns As New NativeBuiltinType(BuiltinType.NativeByte)
        Dim it As New NativeSymbolIterator()
        Dim list As List(Of NativeSymbolRelationship) = it.FindAllNativeSymbolRelationships(ns)

        Assert.Equal(1, list.Count)
        EnsureIsSymbol(ns, list)
    End Sub

    ''' <summary>
    ''' Make sure the parent is returned as a parent
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub FindAllRelationships2()
        Dim child As New NativeBuiltinType(BuiltinType.NativeByte)
        Dim par As New NativePointer(child)
        Dim it As New NativeSymbolIterator()
        Dim list As List(Of NativeSymbolRelationship) = it.FindAllNativeSymbolRelationships(par)

        Assert.Equal(2, list.Count)
        EnsureIsSymbol(par, list)
        EnsureIsSymbol(child, list)
        EnsureIsParent(par, list)
    End Sub

    ''' <summary>
    ''' Recursive relatioship should work just fine even though this tree is not techinally legal
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub FindAllRelationships3()
        Dim ptr1 As New NativePointer()
        Dim ptr2 As New NativePointer(ptr1)
        ptr1.RealType = ptr2

        Dim it As New NativeSymbolIterator()
        Dim list As List(Of NativeSymbolRelationship) = it.FindAllNativeSymbolRelationships(ptr1)
        EnsureIsSymbol(ptr1, list)
        EnsureIsSymbol(ptr2, list)
    End Sub

    <Fact>
    Public Sub FindAllNativeSymbols1()
        Dim child As New NativeBuiltinType(BuiltinType.NativeByte)
        Dim par As New NativePointer(child)
        Dim it As New NativeSymbolIterator()
        Dim list As List(Of NativeSymbol) = it.FindAllNativeSymbols(par)

        Assert.True(list.Contains(child))
        Assert.True(list.Contains(par))
    End Sub

End Class
