' Copyright (c) Microsoft Corporation.  All rights reserved.
'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports PInvoke


'''<summary>
'''This is a test class for PInvoke.ProcedureFinder and is intended
'''to contain all PInvoke.ProcedureFinder Unit Tests
'''</summary>
<TestClass()> _
Public Class ProcedureFinderTest


    Private testContextInstance As TestContext

    '''<summary>
    '''Gets or sets the test context which provides
    '''information about and functionality for the current test run.
    '''</summary>
    Public Property TestContext() As TestContext
        Get
            Return testContextInstance
        End Get
        Set(ByVal value As TestContext)
            testContextInstance = value
        End Set
    End Property

    <TestMethod()> _
    Public Sub Find1()
        Using finder As New ProcedureFinder()
            Dim name As String = Nothing

            Assert.IsTrue(finder.TryFindDllNameExact("GetProcAddress", name))
            Assert.AreEqual("kernel32.dll", name, True)
            Assert.IsTrue(finder.TryFindDllNameExact("SendMessageW", name))
            Assert.AreEqual("user32.dll", name, True)
        End Using
    End Sub

    <TestMethod()> _
    Public Sub Find2()
        Using finder As New ProcedureFinder()
            Dim name As String = Nothing

            Assert.IsFalse(finder.TryFindDllNameExact("DoesNotExistFunc", name))
        End Using
    End Sub

    <TestMethod()> _
    Public Sub Find3()
        Using finder As New ProcedureFinder()
            Dim name As String = Nothing

            Assert.IsFalse(finder.TryFindDllNameExact("SendMessage", name))
            Assert.IsTrue(finder.TryFindDllNameExact("SendMessageW", name))
            Assert.AreEqual("user32.dll", name, True)
            Assert.IsTrue(finder.TryFindDllName("SendMessage", name))
            Assert.AreEqual("user32.dll", name, True)
        End Using
    End Sub

End Class
