' Copyright (c) Microsoft Corporation.  All rights reserved.
'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports PInvoke
Imports PInvoke.Transform
Imports Xunit

'''<summary>
'''This is a test class for PInvoke.Transform.SalAnalyzer and is intended
'''to contain all PInvoke.Transform.SalAnalyzer Unit Tests
'''</summary>
Public Class SalAnalyzerTest

    '''<summary>
    '''A test for IsIn()
    '''</summary>
    <Fact>
    Public Sub IsInTest()
        Dim sal As New NativeSalAttribute(
            SalEntryType.Pre, SalEntryType.Valid,
            SalEntryType.Pre, SalEntryType.Deref, SalEntryType.ReadOnly)
        Dim target As SalAnalyzer = New SalAnalyzer(sal)

        Assert.True(target.IsIn())
    End Sub

    <Fact>
    Public Sub IsInTest2()
        Dim sal As New NativeSalAttribute(
            SalEntryType.Pre, SalEntryType.Valid,
            SalEntryType.Pre, SalEntryType.Deref, SalEntryType.NotReadOnly)
        Dim target As SalAnalyzer = New SalAnalyzer(sal)

        Assert.False(target.IsIn())
    End Sub

    <Fact>
    Public Sub ValidIn1()
        Dim sal As New NativeSalAttribute(
            SalEntryType.Pre, SalEntryType.Valid)
        Dim analyzer As New SalAnalyzer(sal)
        Assert.True(analyzer.IsValidIn())
        Assert.True(analyzer.IsValidInOnly())
        Assert.False(analyzer.IsValidOut())
        Assert.False(analyzer.IsValidOutOnly)
        Assert.False(analyzer.IsValidInOut)
    End Sub


    <Fact>
    Public Sub ValidIn2()
        Dim sal As New NativeSalAttribute(
            SalEntryType.Pre, SalEntryType.Valid,
            SalEntryType.Post, SalEntryType.Valid, SalEntryType.Deref, SalEntryType.NotReadOnly)
        Dim analyzer As New SalAnalyzer(sal)
        Assert.True(analyzer.IsValidIn())
        Assert.False(analyzer.IsValidInOnly())
        Assert.True(analyzer.IsValidOut())
        Assert.False(analyzer.IsValidOutOnly)
        Assert.True(analyzer.IsValidInOut)
    End Sub

    <Fact>
    Public Sub ValidOut1()
        Dim sal As New NativeSalAttribute(
            SalEntryType.Post, SalEntryType.Valid, SalEntryType.Deref, SalEntryType.NotReadOnly)
        Dim analyzer As New SalAnalyzer(sal)
        Assert.False(analyzer.IsValidIn())
        Assert.False(analyzer.IsValidInOnly())
        Assert.True(analyzer.IsValidOut())
        Assert.True(analyzer.IsValidOutOnly)
        Assert.False(analyzer.IsValidInOut)
    End Sub

    <Fact>
    Public Sub ValidOut2()
        Dim sal As New NativeSalAttribute(
            SalEntryType.Pre, SalEntryType.Valid,
            SalEntryType.Post, SalEntryType.Valid, SalEntryType.Deref, SalEntryType.NotReadOnly)
        Dim analyzer As New SalAnalyzer(sal)
        Assert.True(analyzer.IsValidIn())
        Assert.False(analyzer.IsValidInOnly())
        Assert.True(analyzer.IsValidOut())
        Assert.False(analyzer.IsValidOutOnly)
        Assert.True(analyzer.IsValidInOut)
    End Sub

End Class
