' Copyright (c) Microsoft Corporation.  All rights reserved.
'The following code was generated by Microsoft Visual Studio 2005.
'The test owner should check each test for validity.
Imports System
Imports System.Text
Imports System.Collections.Generic
Imports PInvoke.Parser
Imports Helper = PInvoke.Parser.TokenHelper
Imports Xunit


'''<summary>
'''This is a test class for PInvoke.Parser.TokenHelper and is intended
'''to contain all PInvoke.Parser.TokenHelper Unit Tests
'''</summary>
Public Class TokenHelperTest

    Public Sub VerifyParse(ByVal str As String, ByVal value As Object)
        Dim converted As Object = Nothing
        Assert.True(Helper.TryConvertToNumber(str, converted))
        Assert.Equal(value, converted)
    End Sub

    Public Sub VerifyString(ByVal str As String)
        Dim token As New Token(TokenType.QuotedStringAnsi, """" & str & """")
        Dim converted As String = Nothing
        Assert.True(Helper.TryConvertToString(token, converted))
        Assert.Equal(str, converted)

        token = New Token(TokenType.QuotedStringUnicode, "L""" & str & """")
        Assert.True(Helper.TryConvertToString(token, converted))
        Assert.Equal(str, converted)
    End Sub

    Public Sub VerifyChar(ByVal c As Char)
        Dim token As New Token(TokenType.CharacterAnsi, "'" & c & "'")
        Dim converted As Char = "0"c
        Assert.True(Helper.TryConvertToChar(token, converted))
        Assert.Equal(c, converted)

        token = New Token(TokenType.CharacterUnicode, "L'" & c & "'")
        Assert.True(Helper.TryConvertToChar(token, converted))
        Assert.Equal(c, converted)
    End Sub

    Public Sub VerifyNumber(Of T)(ByVal str As String, ByVal number As T)
        Dim ret As Object = Nothing
        Assert.True(TokenHelper.TryConvertToNumber(str, ret))
        Assert.IsType(Of T)(ret)
        Assert.Equal(number, ret)
    End Sub

    ''' <summary>
    ''' Simple 32 bit numbers
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Signed1()
        Dim val As Object = Nothing
        Assert.True(Helper.TryConvertToNumber("42", val))
        Assert.Equal(42, CInt(val))
        Assert.True(Helper.TryConvertToNumber("400", val))
        Assert.Equal(400, CInt(val))
        Assert.True(Helper.TryConvertToNumber("-1", val))
        Assert.Equal(-1, CInt(val))
    End Sub

    ''' <summary>
    ''' Simple 64 bit number.  Should auto expand into a 64 bit number
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Signed2()
        Dim base As Int64 = 6000000000
        VerifyParse(base.ToString(), base)
        VerifyParse("-" & base.ToString(), -base)
    End Sub

    ''' <summary>
    ''' Long suffix does not force a 64 bit number
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Long1()
        VerifyParse("6L", 6)
        VerifyParse("26L", 26)
        VerifyParse("-26L", -26)
    End Sub

    ''' <summary>
    ''' UL should not force a 64 bit number
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Long2()
        VerifyParse("6UL", CUInt(6))
        VerifyParse("26UL", CUInt(26))
    End Sub

    <Fact>
    Public Sub Float1()
        Dim val As Object = Nothing
        Assert.True(Helper.TryConvertToNumber("6.5F", val))
        Assert.Equal(6.5F, Single.Parse(CStr(val)))
    End Sub

    ''' <summary>
    ''' Make sure that a prefix floating point does not get confused as an octal
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Float2()
        VerifyParse("0.1F", 0.1F)
        VerifyParse("0.2F", 0.2F)
    End Sub


    <Fact>
    Public Sub Exponent1()
        Dim val As Object = Nothing
        Assert.True(Helper.TryConvertToNumber("6e2", val))
        Assert.Equal(600.0F, Single.Parse(CStr(val)))
    End Sub

    <Fact>
    Public Sub Exponent2()
        Dim val As Object = Nothing
        Assert.True(Helper.TryConvertToNumber("6.5e2", val))
        Assert.Equal(650.0F, Single.Parse(CStr(val)))
    End Sub

    <Fact>
    Public Sub Exponent3()
        Dim val As Object = Nothing
        Assert.True(Helper.TryConvertToNumber("6.5e2L", val))
        Assert.Equal(650.0F, Single.Parse(CStr(val)))
    End Sub

    ''' <summary>
    ''' Simple unsigned 32 bit numbers
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Unsigned1()
        Dim val As Object = Nothing
        Dim target As UInt32 = 42
        Assert.True(Helper.TryConvertToNumber("42U", val))
        Assert.Equal(target, UInt32.Parse(CStr(val)))
    End Sub

    ''' <summary>
    ''' Too big to be a UInt32
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Unsigned2()
        Dim base As UInt64 = 6000000000
        VerifyParse(base.ToString() & "U", base)
        VerifyParse(base.ToString() & "u", base)
    End Sub

    ''' <summary>
    ''' Can't convert a 32 negative to a signed number
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Unsigned3()
        Dim val As Object = Nothing
        Assert.True(Helper.TryConvertToNumber("-42", val))
        Assert.Equal(-42, CInt(val))
    End Sub

    ''' <summary>
    ''' Simple octal numbers
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Octal1()
        VerifyParse("01", 1)
        VerifyParse("012", 10)
        VerifyParse("0101", 65)
    End Sub

    ''' <summary>
    ''' Octal numbers with the unsigned suffix
    ''' </summary>
    ''' <remarks></remarks>
    <Fact>
    Public Sub Octal2()
        VerifyParse("012U", CUInt(10))
        VerifyParse("01u", CUInt(1))
    End Sub


    <Fact>
    Public Sub Invalid1()
        Dim val As Object = Nothing
        Assert.False(Helper.TryConvertToNumber("aoo", val))
    End Sub

    <Fact>
    Public Sub CallingConvention()
        Assert.True(Helper.IsCallTypeModifier(TokenType.CDeclarationCallKeyword))
        Assert.True(Helper.IsCallTypeModifier(TokenType.StandardCallKeyword))
        Assert.True(Helper.IsCallTypeModifier(TokenType.ClrCallKeyword))
        Assert.True(Helper.IsCallTypeModifier(TokenType.InlineKeyword))
        Assert.True(Helper.IsCallTypeModifier(TokenType.PascalCallKeyword))
    End Sub

    <Fact>
    Public Sub String1()
        VerifyString("foo")
        VerifyString("baaoeuaoeu""")
        VerifyString("aoeu13AEuaoeu'")
    End Sub

    <Fact>
    Public Sub Char1()
        VerifyChar("a"c)
        VerifyChar("b"c)
        VerifyChar(ControlChars.Lf)
        VerifyChar(ChrW(55))
    End Sub

    <Fact>
    Public Sub Force64_1()
        VerifyNumber("4i64", 4L)
        VerifyNumber("999999999999999999i64", 999999999999999999L)
    End Sub

    <Fact>
    Public Sub Force64_2()
        VerifyNumber("4ui64", CULng(4L))
        VerifyNumber("999999999999999999ui64", CULng(999999999999999999L))
    End Sub


End Class
